import React from 'react';
import Layout from '../components/Layout';

function InfoTCA() {
    return (
        <Layout>
            <div className="text-white">
                <h1 className="text-3xl font-bold mb-5">INFORMACIÓ TCA</h1>
                <p>
                    Els trastorns de la conducta alimentària i de la ingesta d'aliments es caracteritzen per una alteració persistent a l'alimentació o al comportament relacionat amb l'alimentació que porta a una alteració en el consum o en l'absorció dels aliments i que causa un deteriorament significatiu de la salut física o del funcionament psicosocial (APA, 2014). Dins d’aquest conjunt de trastorns trobem la pica, el trastorn de ruminació, el trastorn d'evitació/restricció de la ingesta d'aliments, l'anorèxia nerviosa, la bulímia nerviosa i el trastorn de fartaneres, els quals conformen un esquema de classificació que és mútuament excloent, doncs malgrat les característiques psicològiques i de comportament comuns, els trastorns difereixen substancialment en el curs clínic, els resultats i les necessitats de tractament, amb excepció de la pica (APA, 2014).
                </p>
                <h2 className="text-xl font-bold mt-8">PICA</h2>
                <p>
                    La principal característica de la pica és la ingestió persistent de substàncies no nutritives i no alimentàries (el diagnòstic de la pica no fa referència a la ingestió de productes de la dieta amb un mínim contingut nutritiu) durant un període mínim d'1 mes que és prou greu per justificar l'atenció clínica, i normalment no existeix una aversió al menjar en general (APA, 2014). Les substàncies que típicament es solen ingerir tendeixen a variar amb l'edat i amb la disponibilitat i podrien ser paper, sabó, roba, pèl, cordes, llana, terra, guix, pólvores de talc, pintura, xiclets, metalls, còdols, carbó vegetal o carbó mineral, cendres, fang, midó o gel (APA, 2014). La ingestió de substàncies no nutritives i no alimentàries ha de ser inapropiada per al grau de desenvolupament, per això es recomana una edat mínima de dos anys per al diagnòstic de pica, per poder excloure l'hàbit d'emportar-se objectes a la boca, propi del desenvolupament normal dels nens, que els poden acabar ingerint (APA, 2014), però pot iniciar tant a la infància, l'adolescència com a l'edat adulta, encara que el més freqüent és l'inici a la infància (APA, 2014), i no ha de formar part d'una pràctica culturalment o socialment acceptada (APA, 2014). La ingestió de substàncies no nutritives i no alimentàries pot ser una característica associada a altres trastorns mentals, sobretot si s’inicia en l’edat adulta (APA, 2014), si es dona exclusivament en aquest context caldria fer un diagnòstic diferenciat de pica només si el comportament alimentari és prou greu o si requereix atenció clínica addicional (APA, 2014). Durant l'embaràs també es pot manifestar la ingestió de substàncies no nutritives i no alimentàries, i hi pot haver antulls específics, però el diagnòstic de pica durant l'embaràs només és apropiat si aquests desitjos porten a la ingestió de substàncies no nutritives i no alimentàries fins al punt que aquesta ingestió suposi riscos clínics potencials (APA, 2014).
                </p>
                <h2 className="text-xl font-bold mt-8">TRASTORN DE RUMINACIÓ</h2>
                <p>La característica principal del trastorn de ruminació és la regurgitació repetida d'aliments, el menjar empassat prèviament, que pot estar parcialment digerit, es torna a la boca aparentment sense nàusees, arcades involuntàries ni desagradat, aquest es pot tornar a mastegar per després escopir-se de la boca o empassar-se (APA, 2014), durant un període mínim d'un mes, essent freqüent i produint-se almenys força vegades per setmana, típicament diàriament (APA, 2014).</p>
                <p>El trastorn no s'explica millor per una afecció gastrointestinal o una altra afecció mèdica associada i no es produeix exclusivament durant el curs d'una anorèxia nerviosa, una bulímia nerviosa, un trastorn d'atracaments o un trastorn d'evitació/restricció de la ingestió d'aliments (APA, 2014).</p>
                <p>En el cas de que els símptomes es produeixin en el context d'un altre trastorn mental, aquests han de ser prou greus per justificar una atenció clínica addicional i representar un aspecte primordial de la presentació de l'individu que requereix la intervenció (APA, 2014).</p>
                <p>El trastorn es pot diagnosticar durant tota la vida, particularment en els individus que presenten també discapacitat intel·lectual (APA, 2014).</p>
                <p>Els individus poden descriure el comportament com a habitual o fora del seu control (APA, 2014).</p>
                <p>Es pot produir malnutrició, en nens, adolescents i adults, a causa de la imminent la regurgitació i expulsió dels aliments després de cada ingesta (APA, 2014) i quan la regurgitació s'acompanya d'una restricció de la ingesta, degut a que intentaran evitar menjar amb altres persones pel conegut rebuig social que existeix cap a aquest comportament (APA, 2014).</p>
                <h2 className="text-xl font-bold mt-8">TRASTORN D’EVITACIÓ/RESTRICCIÓ DE LA INGESTA D’ALIMENTS</h2>
                <p>La principal característica diagnòstica del trastorn d'evitació/restricció de la ingesta d'aliments és l'evitació o la restricció de la presa d'aliments, per a que aquest criteri es compleixi han de ser presents una o més de les característiques principals següents: pèrdua de pes significativa (valoració clínica), deficiència nutritiva significativa (valoració clínica), dependència de l'alimentació enteral o de suplements nutricionals orals (en absència d'una afecció mèdica subjacent), o una marcada interferència en el funcionament psicosocial (menjar amb altres, mantenir relacions) (APA, 2014).</p>
                <p>L'evitació o la restricció d'aliments relacionada amb la manca de disponibilitat d'aliments o amb pràctiques culturals, no són inclosos dins d’aquest trastorn, ni els comportaments propis del desenvolupament normal (APA, 2014).</p>
                <p>El trastorn no s'explicaria millor per una preocupació excessiva per la constitució o el pes corporal, ni per trastorns mentals o factors clínics concurrents (APA, 2014).</p>
                <p>L'evitació o restricció d'aliments associada a la ingesta insuficient de menjar o a la manca d'interès per alimentar-se es produeix sovint a la lactància o a la primera infància i pot persistir en l'edat adulta (APA, 2014).</p>
                <h2 className="text-xl font-bold mt-8">ANORÈXIA NERVIOSA</h2>
                <p>L'anorèxia nerviosa té tres característiques bàsiques: la restricció de la ingesta energètica persistent, la por intensa a guanyar pes o engreixar-se o un comportament persistent que interfereix amb l'augment de pes, i l'alteració de la manera de percebre el pes i la constitució propis (APA, 2014).</p>
                <p>L'individu manté un pes corporal que està per sota del nivell mínim normal per a la seva edat, sexe, fase de desenvolupament i salut física, que es mesura a través de l'índex de massa corporal (IMC; pes en quilograms / alçada en metres2) (APA, 2014), on el límit inferior és de 18’5 Kg/m2 (OMS), i que menor a 17,0 kg/m2 indica un pes significativament baix (OMS). Amb nens i adolescents es mesura amb percentils de IMC (APA, 2014). Però per tenir una valoració optima s’haurien de considerar les guies numèriques disponibles a més de la constitució física de l'individu, els antecedents referents al pes i qualsevol possible alteració fisiològica (APA, 2014).</p>
                <p>Els individus amb aquest trastorn solen tenir por intensa a guanyar pes o engreixar-se, que no s'alleuja amb la pèrdua de pes, sinó que amb aquesta pèrdua la preocupació fins i tot pot augmentar (APA, 2014). Els individus més joves amb anorèxia nerviosa, així com alguns adults, poden no reconèixer ni admetre aquesta por (APA, 2014).</p>
                <p>La percepció i la importància del pes corporal i la constitució estan distorsionades en aquests individus, podent sentir que tenen excés de pes en general, que estan primes però els preocupa que algunes parts del seu cos, particularment l'abdomen, les natges i les cuixes, estan "massa grossos", i poden emprar diferents tècniques per valorar la talla o el pes corporal, com pesar-se amb freqüència, mesurar obsessivament parts del cos i fer servir insistentment el mirall per comprovar zones de "greix" (APA, 2014), depenent d’aquesta percepció la seva autoestima (APA, 2014).</p>
                <p>La pèrdua de pes la veuen sovint com un èxit impressionant i un signe d'extraordinària autodisciplina, mentre que l'augment de pes el perceben com un fracàs inacceptable de l'autocontrol (APA, 2014), i tot i que alguns individus amb aquest trastorn poden admetre que estan prims, sovint no reconeixen les greus conseqüències mèdiques del seu estat de desnutrició (APA, 2014), és a dir, no tenen un concepte clar del problema o directament ho neguen. En conseqüència, sol ser important obtenir informació dels membres de la família o altres fonts per avaluar els antecedents de la pèrdua de pes i altres característiques de la malaltia (APA, 2014).</p>
                <p>Moltes persones amb anorèxia nerviosa tenen signes i símptomes depressius, com ara estat d’ànim deprimit, aïllament social, irritabilitat, insomni i disminució de l'interès pel sexe, quan tenen un pes molt baix (APA, 2014), així com els símptomes obsessiu-compulsius, estiguin o no relacionats amb l'alimentació, són sovint destacats (APA, 2014).</p>
                <p>Altres característiques que a vegades s'associen a l'anorèxia nerviosa són la preocupació per menjar en públic, la sensació d'ineficàcia, un fort desig de controlar allò que els envolta, el pensament inflexible, una espontaneïtat social limitada i una contenció excessiva de l'expressió emocional (APA, 2014).</p>
                <p>En l'anorèxia nerviosa trobem dos subtipus; amb restricció o amb fartaneres/purgues, on l'intercanvi entre subtipus durant el curs del trastorn no és infreqüent (APA, 2014). La majoria d'individus amb el tipus d'anorèxia amb fartaneres/purgues, per una banda s'afarten de menjar, i per altre es purguen a través del vòmit autoprovocat o la utilització incorrecta de laxants, diürètics o ènemes, els quals poden causar alteracions que generen resultats analítics anormals; no obstant això, alguns individus amb anorèxia nerviosa no mostren anomalies a les proves de laboratori (APA, 2014). Però també es pot donar la situació de purgues sense fartaneres. Aquests individus poden mostrar nivells superiors d'impulsivitat i són més propensos a abusar de l'alcohol i d'altres drogues (APA, 2014), a diferència dels que pateixen anorèxia nerviosa tipus restrictiu. Finalment, també podem trobar un subgrup d’individus amb anorèxia nerviosa que presenta nivells excessius d’activitat física, doncs l'augment d’aquesta sovint precedeix l'inici del trastorn, en el transcurs del trastorn, l'activitat augmentada accelera la pèrdua de pes, i durant el tractament, l'activitat excessiva pot ser difícil de controlar i, per tant, posa en risc la recuperació del pes (APA, 2014).</p>
                <h2 className="text-xl font-bold mt-8">BULÍMIA NERVIOSA</h2>
                <p>Hi ha tres característiques principals de la bulímia nerviosa: els episodis recurrents de fartaneres (ingestió, en un període determinat de temps, generalment inferior a 2 hores, d'una quantitat d'aliments que és clarament superior a la que la majoria de persones ingeririen en un període similar i en circumstàncies semblants, acompanyat d'una sensació de manca de control, on alguns individus descriuen característiques dissociatives durant o després dels episodis d'atracaments (APA, 2014)), els comportaments compensatoris inapropiats i recurrents per evitar l'augment de pes, els quals s'han de produir, de mitjana, almenys una vegada a la setmana durant 3 mesos, i l'autoavaluació que es veu influïda indegudament pel pes i la constitució corporal (APA, 2014).</p>
                <p>Els individus amb bulímia nerviosa se senten típicament avergonyits dels seus problemes alimentaris i intenten ocultar els seus símptomes, de manera que les fartaneres solen produir-se d'amagat o el més discretament possible, i aquests no finalitzen fins que l'individu es sent incòmode o fins i tot adolorit, ple (APA, 2014). L'antecedent més freqüent de les fartaneres és el sentiment negatiu, però també hi ha altres desencadenants com els factors estressants interpersonals, la restricció de la dieta, els sentiments negatius sobre el pes corporal, la constitució corporal i els aliments, i l'avorriment (APA, 2014). Les fartaneres poden minimitzar o mitigar els factors que van precipitar l'episodi a curt termini, però sovint tenen conseqüències a llarg termini, com l'autoavaluació negativa i la disfòria (APA, 2014).</p>
                <p>Molts individus amb bulímia nerviosa empren diversos mètodes per compensar les fartaneres, com vomitar (el quals és el més freqüent, doncs entre els efectes immediats de vomitar hi ha l'alleujament del malestar físic i la reducció de la por de guanyar pes, i en alguns casos, vomitar és una finalitat en si mateixa i l'individu es farta per tal de vomitar, o vomitarà després d'ingerir una petita quantitat de menjar (APA, 2014). Els individus amb bulímia nerviosa poden utilitzar gran varietat de mètodes per provocar el vòmit, però el més freqüent és l'ús dels dits o d'instruments per estimular el reflex nauseós, tornant-se hàbils per provocar-se el vòmit i finalment són capaços de vomitar a voluntat (APA, 2014).), la utilització incorrecta de laxants i diürètics, ènemes, prendre hormona tiroidal per intentar evitar guanyar pes, els individus amb diabetis mellitus i bulímia nerviosa poden ometre o reduir les dosis d'insulina per reduir el metabolisme dels aliments consumits durant les fartaneres, els individus amb bulímia nerviosa poden dejunar un o més dies, o fer exercici excessiu (és excessiu quan interfereix de manera significativa amb altres activitats importants, quan es realitza en moments o en llocs inapropiats, o quan es continua fent malgrat alguna lesió o malgrat altres complicacions mèdiques) per intentar evitar l'augment de pes (APA, 2014).</p>
                <p>Les persones amb bulímia nerviosa li concedeixen una importància excessiva al pes o a la constitució corporal en la seva autoavaluació, i aquests factors són, en general, extremadament importants per determinar-ne l'autoestima, tot i que, els individus amb bulímia nerviosa solen estar dins del rang de pes normal o tenir sobrepès (IMC [18’5 , 30] en els adults) (APA, 2014). No s'hauria de fer un diagnòstic de bulímia nerviosa si el trastorn es produeix només durant episodis d'anorèxia nerviosa (APA, 2014).</p>
                <p>Les irregularitats menstruals o l'amenorrea es produeixen sovint en les dones amb bulímia nerviosa (APA, 2014).</p>
                <h2 className="text-xl font-bold mt-8">TRASTORN DE FARTANERES</h2>
                <p>La característica principal del trastorn de fartaneres són episodis recurrents (almenys una vegada a la setmana durant tres mesos, de mitjana) de fartaneres (Criteri D) (APA,2014). Un "episodi de fartaneres" consisteix en la ingesta en un període de temps determinat (període delimitat, generalment inferior a les 2 hores) d'una quantitat d'aliments que és clarament superior a la que la majoria de les persones ingeriria en un període similar i en circumstàncies semblants (Criteri A1) (APA,2014). Picar, és a dir, menjar contínuament en petites quantitats durant el dia no es consideraria un fartanera (APA,2014).</p>
                <p>El consum excessiu d'aliments ha d'anar acompanyat d'una sensació de manca de control (incapacitat per contenir-se i no menjar, o per parar de menjar una vegada començat) (Criteri A2) (APA,2014). Si els individus refereixen que han deixat d'esforçar-se per controlar la seva ingesta, s'hauria de considerar que hi ha pèrdua de control (APA,2014). En alguns casos, les fartaneres també es poden planificar (APA,2014).</p>
                <p>Els afartaments han de caracteritzar-se més per una alteració de la quantitat d'aliments consumits que no pas pel desig d'un nutrient específic però tots comparteixen un malestar intens (Criteri C) (APA,2014) i, tres o més dels fets següents: menjar molt més ràpidament del normal, menjar fins a sentir-se desagradablement ple, menjar grans quantitats d'aliments sense tenir gana, menjar només a causa de la vergonya que se sent per la quantitat que s'ingereix, i sentir-se després a disgust amb un mateix, deprimit o molt avergonyit (Criteri B) (APA,2014).</p>
                <p>Els individus amb trastorn de fartaneres es senten típicament avergonyits pels seus problemes alimentaris i intenten amagar-ne els símptomes, de manera que les fartaneres solen produir-se d'amagat o el més discretament possible, i aquestes no finalitzen fins que l'individu es sent incòmode, o fins i tot adolorit, ple (APA,2014). Hi ha diversos desencadenants de les fartaneres, el sentiment negatiu, el qual és el principal desencadenant, els factors estressants interpersonals, la restricció de la dieta, els sentiments negatius sobre el pes corporal, la constitució corporal i els aliments i l'avorriment (APA,2014).</p>
                <p>Pel que fa als individus, el trastorn de fartaneres es produeix normalment en persones de pes normal/sobrepès i en persones obeses (APA,2014).</p>

            </div>
        </Layout>
    );
}

export default InfoTCA;
