import React from 'react';
import Layout from '../components/Layout';

const LeyProteccionDatosPage = () => {
  return (
    <Layout>
      <h1 className="text-3xl font-bold mb-5">LLEI DE PROTECCIÓ DE DADES</h1>
      <p>Conforme amb el Reglament General de Protecció de Dades RGPD UE 679/2016 i la Llei Orgànica 3/2018 del 5 de desembre, de Protecció de Dades Personals i Garantia dels Drets Digitals, se li facilita la següent informació sobre el tractament de les seves dades de caràcter personal:</p>
      <p>FINALITAT: A Test TCA LLURBA tractem les dades de caràcter personal que ens facilita per prestar-li serveis d'avaluació psicològica, així com per mantenir-lo informat sobre qüestions relatives a l’avaluació al qual s'ha sotmès. No es realitza cap perfil comercial a partir d'aquesta informació. Les seves dades de caràcter personal seran conservades mentre siguin útils per a la finalitat indicada, i, en tot cas, durant els terminis legals i el temps necessari per atendre possibles responsabilitats derivades del tractament.</p>
      <p>LEGITIMACIÓ: El tractament de les seves dades de caràcter personal es basa en l'execució d'un contracte en què l'interessat és part o per a l'aplicació a petició d'aquest de mesures precontractuals. A més, hem de tractar les seves dades per complir amb una obligació legal aplicable al responsable del tractament, de conformitat amb el que estableix el Reglament General de Protecció de Dades RGPD UE 679/2016 (Art. 6.1. B i C) i la Llei Orgànica 3/2018 del 5 de desembre, de Protecció de Dades Personals i Garantia dels Drets Digitals (LOPDPGDD). Resulta d'aplicació la llei 41/2002, del 14 de novembre, bàsica reguladora de l'autonomia del pacient i dels drets i obligacions en matèria d'informació i documentació clínica, en relació amb els articles 14-19, relatius al tractament d'historials clínics. Existeix l'obligació de facilitar les dades de caràcter personal o, en cas contrari, no es pot prestar l'atenció i/o tractament psicològic sol·licitat.</p>
      <p>DESTINATARIS: Les dades no es comunicaran a cap tercer aliè a l'Entitat, llevat de l'obligació legal. No obstant això, l'informem que tercers proveïdors poden tenir accedir a les seves dades personals, en qualitat d'encarregats del tractament, en el marc de la prestació d'un servei per a l'Entitat Responsable del Tractament. A més dels anteriors, l'Entitat podrà realitzar cessió o comunicació de dades personals a Hospitals, Entitats Asseguradores de Salut i a l'Administració Pública competent en la matèria. No hi ha previsió de transferència de dades a tercers països. No es prenen decisions d'adequació, garanties, normes corporatives vinculants o situacions específiques aplicables.</p>
      <p>DRETS: Les persones interessades tenen dret a obtenir l'accés a les seves dades personals, així com a sol·licitar la rectificació de les dades inexactes o, si escau, sol·licitar-ne la supressió quan, entre altres motius, les dades ja no siguin necessàries per als fins que van ser recollides. En determinades circumstàncies, les persones interessades poden sol·licitar la limitació del tractament de les seves dades, en aquest cas només les conservarem per a l'exercici o defensa de reclamacions. Així mateix, i per motius relacionats amb la seva situació particular, les persones interessades poden oposar-se al tractament de les seves dades, en aquest cas la seva informació personal deixarà de ser tractada, per a aquells fins respecte dels quals hagi manifestat la seva oposició. Quan sigui tècnicament possible, la persona interessada pot sol·licitar la portabilitat de les seves dades a un altre responsable del tractament. Per exercir aquests drets, de conformitat amb la legislació vigent, les persones interessades poden dirigir-se per correu postal, adjuntant còpia d'un document acreditatiu de la seva identitat (DNI), a l'adreça postal que figura més amunt.</p>
      <p>Vostè té dret a presentar una Reclamació davant l'Autoritat de Control: Agència Espanyola de Protecció de Dades (www.agpd.es). C/ Jorge Juan, 6. 28001 Madrid. Tel. 901100099; 912663517.</p>
    </Layout>
  );
};

export default LeyProteccionDatosPage;
