import React from 'react';
import Layout from '../components/Layout';

const TRAnorexiaNerviosaPage = () => {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto">
        <div className="mt-8 mb-4">
          <h2 className="text-3xl font-bold">ANORÈXIA NERVIOSA</h2>
        </div>
        <p className="my-4">L'anorèxia nerviosa té tres característiques bàsiques: la restricció de la ingesta energètica persistent, la por intensa a guanyar pes o engreixar-se o un comportament persistent que interfereix amb l'augment de pes, i l'alteració de la manera de percebre el pes i la constitució propis (APA, 2014).</p>
        <p className="my-4">L'individu manté un pes corporal que està per sota del nivell mínim normal per a la seva edat, sexe, fase de desenvolupament i salut física, que es mesura a través de l'índex de massa corporal (IMC; pes en quilograms / alçada en metres2) (APA, 2014), on el límit inferior és de 18’5 Kg/m2 (OMS), i que menor a 17,0 kg/m2 indica un pes significativament baix (OMS). Amb nens i adolescents es mesura amb percentils de IMC (APA, 2014). Però per tenir una valoració optima s’haurien de considerar les guies numèriques disponibles a més de la constitució física de l'individu, els antecedents referents al pes i qualsevol possible alteració fisiològica (APA, 2014).</p>
        <p className="my-4">Els individus amb aquest trastorn solen tenir por intensa a guanyar pes o engreixar-se, que no s'alleuja amb la pèrdua de pes, sinó que amb aquesta pèrdua la preocupació fins i tot pot augmentar (APA, 2014). Els individus més joves amb anorèxia nerviosa, així com alguns adults, poden no reconèixer ni admetre aquesta por (APA, 2014).</p>
        <p className="my-4">La percepció i la importància del pes corporal i la constitució estan distorsionades en aquests individus, podent sentir que tenen excés de pes en general, que estan primes però els preocupa que algunes parts del seu cos, particularment l'abdomen, les natges i les cuixes, estan "massa grossos", i poden emprar diferents tècniques per valorar la talla o el pes corporal, com pesar-se amb freqüència, mesurar obsessivament parts del cos i fer servir insistentment el mirall per comprovar zones de "greix" (APA, 2014), depenent d’aquesta percepció la seva autoestima (APA, 2014).</p>
        <p className="my-4">La pèrdua de pes la veuen sovint com un èxit impressionant i un signe d'extraordinària autodisciplina, mentre que l'augment de pes el perceben com un fracàs inacceptable de l'autocontrol (APA, 2014), i tot i que alguns individus amb aquest trastorn poden admetre que estan prims, sovint no reconeixen les greus conseqüències mèdiques del seu estat de desnutrició (APA, 2014), és a dir, no tenen un concepte clar del problema o directament ho neguen. En conseqüència, sol ser important obtenir informació dels membres de la família o altres fonts per avaluar els antecedents de la pèrdua de pes i altres característiques de la malaltia (APA, 2014).</p>
        <p className="my-4">Moltes persones amb anorèxia nerviosa tenen signes i símptomes depressius, com ara estat d’ànim deprimit, aïllament social, irritabilitat, insomni i disminució de l'interès pel sexe, quan tenen un pes molt baix (APA, 2014), així com els símptomes obsessiu-compulsius, estiguin o no relacionats amb l'alimentació, són sovint destacats (APA, 2014).</p>
        <p className="my-4">Altres característiques que a vegades s'associen a l'anorèxia nerviosa són la preocupació per menjar en públic, la sensació d'ineficàcia, un fort desig de controlar allò que els envolta, el pensament inflexible, una espontaneïtat social limitada i una contenció excessiva de l'expressió emocional (APA, 2014).</p>
        <p className="my-4">En l'anorèxia nerviosa trobem dos subtipus; amb restricció o amb fartaneres/purgues, on l'intercanvi entre subtipus durant el curs del trastorn no és infreqüent (APA, 2014). La majoria d'individus amb el tipus d'anorèxia amb fartaneres/purgues, per una banda s'afarten de menjar, i per altre es purguen a través del vòmit autoprovocat o la utilització incorrecta de laxants, diürètics o ènemes, els quals poden causar alteracions que generen resultats analítics anormals; no obstant això, alguns individus amb anorèxia nerviosa no mostren anomalies a les proves de laboratori (APA, 2014). Però també es pot donar la situació de purgues sense fartaneres. Aquests individus poden mostrar nivells superiors d'impulsivitat i són més propensos a abusar de l'alcohol i d'altres drogues (APA, 2014), a diferència dels que pateixen anorèxia nerviosa tipus restrictiu. Finalment, també podem trobar un subgrup d’individus amb anorèxia nerviosa que presenta nivells excessius d’activitat física, doncs l'augment d’aquesta sovint precedeix l'inici del trastorn, en el transcurs del trastorn, l'activitat augmentada accelera la pèrdua de pes, i durant el tractament, l'activitat excessiva pot ser difícil de controlar i, per tant, posa en risc la recuperació del pes (APA, 2014).</p>
      </div>
    </Layout>
  );
};

export default TRAnorexiaNerviosaPage;