import React from 'react';
import Layout from '../components/Layout';

const TRBulimiaNerviosaPage = () => {
  return (
    <Layout>
      <h2 className="text-xl font-bold mt-8">BULÍMIA NERVIOSA</h2>
      <p>Hi ha tres característiques principals de la bulímia nerviosa: els episodis recurrents de fartaneres (ingestió, en un període determinat de temps, generalment inferior a 2 hores, d'una quantitat d'aliments que és clarament superior a la que la majoria de persones ingeririen en un període similar i en circumstàncies semblants, acompanyat d'una sensació de manca de control, on alguns individus descriuen característiques dissociatives durant o després dels episodis d'atracaments (APA, 2014)), els comportaments compensatoris inapropiats i recurrents per evitar l'augment de pes, els quals s'han de produir, de mitjana, almenys una vegada a la setmana durant 3 mesos, i l'autoavaluació que es veu influïda indegudament pel pes i la constitució corporal (APA, 2014).</p>
      <p>Els individus amb bulímia nerviosa se senten típicament avergonyits dels seus problemes alimentaris i intenten ocultar els seus símptomes, de manera que les fartaneres solen produir-se d'amagat o el més discretament possible, i aquests no finalitzen fins que l'individu es sent incòmode o fins i tot adolorit, ple (APA, 2014). L'antecedent més freqüent de les fartaneres és el sentiment negatiu, però també hi ha altres desencadenants com els factors estressants interpersonals, la restricció de la dieta, els sentiments negatius sobre el pes corporal, la constitució corporal i els aliments, i l'avorriment (APA, 2014). Les fartaneres poden minimitzar o mitigar els factors que van precipitar l'episodi a curt termini, però sovint tenen conseqüències a llarg termini, com l'autoavaluació negativa i la disfòria (APA, 2014).</p>
      <p>Molts individus amb bulímia nerviosa empren diversos mètodes per compensar les fartaneres, com vomitar (el quals és el més freqüent, doncs entre els efectes immediats de vomitar hi ha l'alleujament del malestar físic i la reducció de la por de guanyar pes, i en alguns casos, vomitar és una finalitat en si mateixa i l'individu es farta per tal de vomitar, o vomitarà després d'ingerir una petita quantitat de menjar (APA, 2014). Els individus amb bulímia nerviosa poden utilitzar gran varietat de mètodes per provocar el vòmit, però el més freqüent és l'ús dels dits o d'instruments per estimular el reflex nauseós, tornant-se hàbils per provocar-se el vòmit i finalment són capaços de vomitar a voluntat (APA, 2014).), la utilització incorrecta de laxants i diürètics, ènemes, prendre hormona tiroidal per intentar evitar guanyar pes, els individus amb diabetis mellitus i bulímia nerviosa poden ometre o reduir les dosis d'insulina per reduir el metabolisme dels aliments consumits durant les fartaneres, els individus amb bulímia nerviosa poden dejunar un o més dies, o fer exercici excessiu (és excessiu quan interfereix de manera significativa amb altres activitats importants, quan es realitza en moments o en llocs inapropiats, o quan es continua fent malgrat alguna lesió o malgrat altres complicacions mèdiques) per intentar evitar l'augment de pes (APA, 2014).</p>
      <p>Les persones amb bulímia nerviosa li concedeixen una importància excessiva al pes o a la constitució corporal en la seva autoavaluació, i aquests factors són, en general, extremadament importants per determinar-ne l'autoestima, tot i que, els individus amb bulímia nerviosa solen estar dins del rang de pes normal o tenir sobrepès (IMC [18’5 , 30] en els adults) (APA, 2014). No s'hauria de fer un diagnòstic de bulímia nerviosa si el trastorn es produeix només durant episodis d'anorèxia nerviosa (APA, 2014).</p>
    </Layout>
  );
};

export default TRBulimiaNerviosaPage;