import React, { useState } from 'react';
export const Values = () =>{
    const responses = useState( {
        "AS":{
            'value':0,
            'bool':false,
            'limit':16
            },
        "AP":{
            'value':0,
            'bool':false,
            'limit':10
            },
        "SC":{
            'value':0,
            'bool':false,
            'limit':8
            },
        "SD":{
            'value':0,
            'bool':false,
            'limit':8
            },
        "CS":{
            'value':0,
            'bool':false,
            'limit':5
            },
        "P":{
            'value':0,
            'bool':false,
            'limit':12
            },
        "F":{
            'value':0,
            'bool':false,
            'limit':10
            },
        "RM":{
            'value':0,
            'bool':false,
            'limit':13
            },
        "R":{
            'value':0,
            'bool':false,
            'limit':2
            },
	   "D":{
            'value':0,
            'bool':false,
            'limit':16
            },
        "EF":{
            'value':0,
            'bool':false,
            'limit':13,
            },
        "CM":{
            'value':0,
            'bool':false,
            'limit':11,
            },
        "V":{
            'value':0,
            'bool':false,
            'limit':16,
            },
        "SOAA":{
            'value':0,
            'bool':false,
            'limit':8,
            },
        "CSNN":{
            'value':0,
            'bool':false,
            'limit':15,
            },
        "FG":{
            'value':0,
            'bool':false,
            'limit':13,
            },
        "FC":{
            'value':0,
            'bool':false,
            'limit':10,
            },
        "X":{
            'value':0,
            'bool':false,
            'limit':5,
            },
  });
  return responses;
}
export default Values;
